#!/bin/sh

# Build 1.0 3/21/23 - Looks for local users and does the math to find out how many days remain, warns the user to change password based on time frame
# Once the user is warned it prompts them to change the password
# Build 1.1 3/27/23 - Changed Echo to reflect password date and shortened the notfication time from 30 days to 20 Days
# Build 1.2 5/22/23 - Path of Ventura Change password button has changed, adjusted it for Ventura

# Built by Cody Keats 

MAX_PASSWORD_AGE=60
TEMP_PLIST="/tmp/pwdpolicy.plist"

for user in $(/bin/ls -la /dev/console | /usr/bin/cut -d ' ' -f 4); do
    
    dscl . read /Users/"$user" accountPolicyData | sed '1d' > $TEMP_PLIST
    
    LAST_SET=$(defaults read $TEMP_PLIST passwordLastSetTime | cut -d"." -f 1)
    CURRENT_UNIX_TIME=$(date +"%s")
    
    PASSWORD_LAST_SET_DAYS=$(( LAST_SET / 86400 ))
    CURRENT_TIME_DAYS=$(( CURRENT_UNIX_TIME / 86400 ))
    
    PASSWORD_SET_DAYS=$(( CURRENT_TIME_DAYS - PASSWORD_LAST_SET_DAYS ))
    
    TIME_TO_CHANGE=$(( MAX_PASSWORD_AGE - PASSWORD_SET_DAYS ))

    rm $TEMP_PLIST
    
done

getUID=$(id -u "$user")

if [ "$TIME_TO_CHANGE" -gt 20 ];then
	echo "The password for $user is outside the warning period of 20 days. Password expires in $TIME_TO_CHANGE days."
	exit 0
elif [ "$TIME_TO_CHANGE" -le 20 ] && [ "$TIME_TO_CHANGE" -gt 1 ];
then
	echo "The password for $user expires in $TIME_TO_CHANGE days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in '$TIME_TO_CHANGE' days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Status Check" with text buttons {"Maybe Later", "Change Now"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Settings" to delay 2' -e 'tell application "System Events" to tell process "System Settings" to click UI Element 4 of group 1 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Users & Groups"' -e 'tell application "System Events" to tell process "System Settings" to click UI Element 3 of group 1 of scroll area 1 of group 1 of sheet 1 of window "Users & Groups"' 2> /dev/null
elif [ "$TIME_TO_CHANGE" = 1 ];
then
	echo "The password for $user expires in 1 day!"	
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires tomorrow!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Status Check" with text buttons {"Maybe Later", "Change Now"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Settings" to delay 2' -e 'tell application "System Events" to tell process "System Settings" to click UI Element 4 of group 1 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Users & Groups"' -e 'tell application "System Events" to tell process "System Settings" to click UI Element 3 of group 1 of scroll area 1 of group 1 of sheet 1 of window "Users & Groups"' 2> /dev/null	
elif [ "$TIME_TO_CHANGE" = 0 ];
then
	echo "The password for $user expires today!"	
	launchctl asuser "$getUID"/usr/bin/osascript -e 'Tell current application to display dialog "Your password expires today!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Status Check" with text buttons {"Maybe Later", "Change Now"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Settings" to delay 2' -e 'tell application "System Events" to tell process "System Settings" to click UI Element 4 of group 1 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Users & Groups"' -e 'tell application "System Events" to tell process "System Settings" to click UI Element 3 of group 1 of scroll area 1 of group 1 of sheet 1 of window "Users & Groups"' 2> /dev/null
elif [ "$TIME_TO_CHANGE" -lt 0 ];
then
	echo "The password for $user has expired!"	
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password has expired! Attempt to change your password or contact the RDTE Helpdesk for help"' 
fi

sleep 120
#Updates Inventory in Jamf
/usr/local/jamf/bin/jamf recon 

exit 0
