#!/bin/sh

MAX_PASSWORD_AGE=60
TEMP_PLIST="/tmp/pwdpolicy.plist"

for user in $(/bin/ls -la /dev/console | /usr/bin/cut -d ' ' -f 4); do
    
    dscl . read /Users/"$user" accountPolicyData | sed '1d' > $TEMP_PLIST
    
    LAST_SET=$(defaults read $TEMP_PLIST passwordLastSetTime | cut -d"." -f 1)
    CURRENT_UNIX_TIME=$(date +"%s")
    
    PASSWORD_LAST_SET_DAYS=$(( LAST_SET / 86400 ))
    CURRENT_TIME_DAYS=$(( CURRENT_UNIX_TIME / 86400 ))
    
    PASSWORD_SET_DAYS=$(( CURRENT_TIME_DAYS - PASSWORD_LAST_SET_DAYS ))
    
    TIME_TO_CHANGE=$(( MAX_PASSWORD_AGE - PASSWORD_SET_DAYS ))

    echo "$user password expires in $TIME_TO_CHANGE days"
    #rm $TEMP_PLIST
    
done

getUID=$(id -u "$user")

if [ "$TIME_TO_CHANGE" -gt 30 ];then
	echo "The password for $user is outside the warning period."
	exit 0
elif [ "$TIME_TO_CHANGE" -le 29 ] && [ "$TIME_TO_CHANGE" -gt 20 ];
then
	echo "The password for $user expires in less than 30 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in less than 30 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 
elif [ "$TIME_TO_CHANGE" -le 19 ] && [ "$TIME_TO_CHANGE" -ge 11 ];
then
	echo "The password for $user expires in less than 20 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in less than 20 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 
	
elif [ "$TIME_TO_CHANGE" -le 10 ] && [ "$TIME_TO_CHANGE" -ge 6 ];
then
	echo "The password for $user expires in less than 10 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in less than 10 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 
	
elif [ "$TIME_TO_CHANGE" = 5 ];
then
	echo "The password for $user expires in 5 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in 5 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 

elif [ "$TIME_TO_CHANGE" = 4 ];
then
	echo "The password for $user expires in 4 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in 4 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 

elif [ "$TIME_TO_CHANGE" = 3 ];
then
	echo "The password for $user expires in 3 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in 3 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 
	
elif [ "$TIME_TO_CHANGE" = 2 ];
then
	echo "The password for $user expires in 2 days!"
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires in 2 days!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 
	
elif [ "$TIME_TO_CHANGE" = 1 ];
then
	echo "The password for $user expires in 1 day!"	
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password expires tomorrow!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 
	
elif [ "$TIME_TO_CHANGE" = 0 ];
then
	echo "The password for $user expires today!"	
	launchctl asuser "$getUID"/usr/bin/osascript -e 'Tell current application to display dialog "Your password expires today!" with icon "Macintosh HD:System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:FileVaultIcon.icns" as alias with title "Password Expiration Warning" with text buttons {"Maybe Later", "Change Password"} cancel button 1 default button 2' -e 'tell application "Finder" to open POSIX file "/System/Library/PreferencePanes/Accounts.prefPane"' -e 'tell application "System Events" to tell process "System Preferences" to delay 1' -e 'tell application "System Events" to tell process "System Preferences" to click button "Change Password…" of tab group 1 of window "Users & Groups"' 	
elif [ "$TIME_TO_CHANGE" -lt 0 ];
then
	echo "The password for $user has expired!"	
	launchctl asuser "$getUID" /usr/bin/osascript -e 'Tell current application to display dialog "Your password has expired! Contact the Helpdesk to gain access"' 
fi

exit 0
